# Part One **OK**

In [10]:
import re
import numpy as np

FILE_NAME = "day_08_input11.txt"

def load_data(file_name):
    file= open(file_name, "r")
    data = [[l for l in line] for line in file.read().splitlines()]
    npdata = np.array(data, dtype='<U5')
    return npdata

def test_antinodes(i, j):
    if i >= 0 and j >= 0 and data.shape[0] > i and data.shape[1] > j:
        if data[i,j] == ".":
            data[i,j] = "#"
        else:
            data[i,j] += "#"
       
def antinodes(i, j):
    i1 = i[0]
    j1 = j[0]
    for i_n, j_n in zip(i[1:], j[1:]):
        i_distance = i_n - i1
        j_distance = j_n - j1

        i1_antinode = i1 - i_distance
        j1_antinode = j1 - j_distance
        test_antinodes(i1_antinode, j1_antinode)

        i_n_antinode = i_n + i_distance
        j_n_antinode = j_n + j_distance
        test_antinodes(i_n_antinode, j_n_antinode)

    if len(i[1:]) > 1:
        antinodes(i[1:],j[1:])

def process(data):
    exceptions_chars = ["#",'.']
    for values in data: 
        for x in values:
            xx = x[0]
            if xx not in exceptions_chars:
                exceptions_chars.append(x)
                starts_with_a_2d = np.char.startswith(data, xx)
                positions_2d = np.where(starts_with_a_2d)
                i, j = positions_2d
                antinodes(i, j)
    contains_hash_2d = np.char.find(data, '#') != -1
    count_hash_cells_2d = np.sum(contains_hash_2d)
    return count_hash_cells_2d

data = load_data(FILE_NAME)
print(process(data))

305


# Part Two **OK**

In [13]:
import re
import numpy as np

FILE_NAME = "day_08_input11.txt"

def load_data(file_name):
    file= open(file_name, "r")
    data = [[l for l in line] for line in file.read().splitlines()]
    npdata = np.array(data, dtype='<U5')
    return npdata

def test_antinodes(i, j, i_distance, j_distance):
    i1_antinode = i - i_distance
    j1_antinode = j - j_distance
    if i1_antinode >= 0 and j1_antinode >= 0 and data.shape[0] > i1_antinode and data.shape[1] > j1_antinode:
        if data[i1_antinode,j1_antinode] == ".":
            data[i1_antinode,j1_antinode] = "#"
        else:
            data[i1_antinode,j1_antinode] += "#"
        test_antinodes(i1_antinode, j1_antinode, i_distance, j_distance)
             
def antinodes(i, j):
    i1 = i[0]
    j1 = j[0]
    for i_n, j_n in zip(i[1:], j[1:]):
        i_distance = i_n - i1
        j_distance = j_n - j1
        test_antinodes(i1, j1, i_distance, j_distance)
        test_antinodes(i_n, j_n, -i_distance, -j_distance)

    if len(i[1:]) > 1:
        antinodes(i[1:],j[1:])
    
def process(data):
    exceptions_chars = ["#",'.']
    for values in data: 
        for x in values:
            xx = x[0]
            if xx not in exceptions_chars:
                exceptions_chars.append(x)
                starts_with_a_2d = np.char.startswith(data, xx)
                positions_2d = np.where(starts_with_a_2d)

                i, j = positions_2d
                antinodes(i, j)
   
    contains_hash_2d = np.char.find(data, '.') == -1
    count_hash_cells_2d = np.sum(contains_hash_2d)
    return count_hash_cells_2d

data = load_data(FILE_NAME)
print(process(data))

1150


version with visual print

In [14]:
import re
import numpy as np

FILE_NAME = "day_08_input11.txt"

def load_data(file_name):
    file= open(file_name, "r")
    data = [[l for l in line] for line in file.read().splitlines()]
    npdata = np.array(data, dtype='<U5')
    return npdata

def test_antinodes(i, j, i_distance, j_distance, a):
    i1_antinode = i - i_distance
    j1_antinode = j - j_distance
    if i1_antinode >= 0 and j1_antinode >= 0 and data.shape[0] > i1_antinode and data.shape[1] > j1_antinode:
        if data[i1_antinode,j1_antinode] == ".":
            data[i1_antinode,j1_antinode] = "#"
        else:
            data[i1_antinode,j1_antinode] += a+"#"
        test_antinodes(i1_antinode, j1_antinode, i_distance, j_distance, a)
        
       
def antinodes(i, j):
    i1 = i[0]
    j1 = j[0]
    a = data[i1,j1]

    for i_n, j_n in zip(i[1:], j[1:]):
        i_distance = i_n - i1
        j_distance = j_n - j1
        test_antinodes(i1, j1, i_distance, j_distance, a)
        test_antinodes(i_n, j_n, -i_distance, -j_distance, a)

    if len(i[1:]) > 1:
        antinodes(i[1:],j[1:])
    
def process(data):
    print(data)
    # for remove duplicates faster run
    exceptions_chars = ["#",'.']
    for values in data: 
        for x in values:
            xx = x[0]
            if xx not in exceptions_chars:
                exceptions_chars.append(x)
                starts_with_a_2d = np.char.startswith(data, xx)
                positions_2d = np.where(starts_with_a_2d)

                i, j = positions_2d
                antinodes(i, j)
    print(data)   
    print(np.char.find(data, '#'))
    contains_hash_2d = np.char.find(data, '.') == -1

    count_hash_cells_2d = np.sum(contains_hash_2d)
    return count_hash_cells_2d

data = load_data(FILE_NAME)
print(process(data))

[['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' 'Y' ... '.' '.' '.']
 ...
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']]
[['.' '.' '#3#3#' ... '#c#l#' '.' '.']
 ['#5#' '.' '#' ... '#' '#zJ##' '.']
 ['.' '#' 'YOU##' ... '.' '.' '#']
 ...
 ['.' '.' '#z#' ... '.' '#' '#']
 ['.' '.' '#' ... '#' '.' '#13#3']
 ['#' '.' '.' ... '.' '#' '#']]
[[-1 -1  0 ...  0 -1 -1]
 [ 0 -1  0 ...  0  0 -1]
 [-1  0  3 ... -1 -1  0]
 ...
 [-1 -1  0 ... -1  0  0]
 [-1 -1  0 ...  0 -1  0]
 [ 0 -1 -1 ... -1  0  0]]
1150
